chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('loadChat', views.loadChat, name="loadChat"),
    path('startChat', views.startChat, name="startChat"),
    path('insertMsg', views.insertMsg, name="insertMsg"),
    path('viewChat/<int:foo>', views.viewChat, name="viewChat"),
    path('delete', views.delete, name="delete"),
    path('deleteAll', views.deleteAll, name="deleteAll"),

]

chitchat/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

handler404 = 'login.views.custom_page_not_found_view'
handler500 = 'login.views.custom_error_view'
handler403 = 'login.views.custom_permission_denied_view'
handler400 = 'login.views.custom_bad_request_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('myprofile.urls')),
    path('', include('chat.urls')),
    path('', include('friends.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path

from . import views

app_name = 'friends'
urlpatterns = [
    path('loadFriends', views.loadFriends, name="loadFriends"),
    path('insertFriendRequest', views.insertFriendRequest, name="insertFriendRequest"),
    path('viewRequestProfile', views.viewRequestProfile, name="viewRequestProfile"),
    path('accept', views.accept, name="accept"),
    path('reject', views.reject, name="reject"),
    path('removeFriend', views.removeFriend, name="removeFriend")

]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.loadLogin, name='loadLogin'),
    path('insertLogin', views.insertLogin, name='insertLogin'),
    path('loadRegister', views.loadRegister, name='loadRegister'),
    path('insertRegister', views.insertRegister, name='insertRegister'),
    path('updatePassword', views.updatePassword, name='updatePassword'),
    path('forgotPassword', views.forgotPassword, name='forgotPassword'),
    path('insertForgotPassword', views.insertForgotPassword, name='insertForgotPassword'),

]

myprofile/urls.py
from django.urls import path

from . import views

app_name = 'myprofile'
urlpatterns = [
    path('loadMyProfile', views.loadMyProfile, name="loadMyProfile"),
    path('insertPersonalInfo', views.insertPersonalInfo, name="insertPersonalInfo"),
    path('insertSocialMediaLink', views.insertSocialMediaLink, name="insertSocialMediaLink"),
    path('insertNewPassword', views.insertNewPassword, name="insertNewPassword"),
    path('insertProfilePhoto', views.insertProfilePhoto, name="insertProfilePhoto"),

]

chat/models.py
from django.db import models
from login.models import Loginmaster, Usermaster


# Create your models here.

class Msgmaster(models.Model):
    msg_From = models.ForeignKey(Loginmaster, on_delete=models.CASCADE, related_name='msg_From', db_column='msg_From')
    msg_To = models.ForeignKey(Loginmaster, on_delete=models.CASCADE, related_name='msg_To', db_column='msg_To')
    msg = models.CharField(max_length=1000, blank=True)
    msgSendTime = models.TimeField(null=True)
    msgSendDate = models.DateField(null=True)
    msgSendBy = models.IntegerField(null=True)

chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sessions.models import Session
from django.http import HttpResponse
from login.models import Usermaster, Loginmaster
from friends.models import FriendRequestmaster
from .models import Msgmaster
from datetime import datetime


# Create your views here.

def loadChat(request):
    try:
        if request.session.has_key('session_loginRole'):
            user = Usermaster.objects.filter(user_LoginId=request.session['session_Id'])
            friendList = FriendRequestmaster.objects.filter(friendRequest_From=request.session['session_Id'],
                                                            friendRequest_Action='accept')
            profilePhotoList = Usermaster.objects.all()

            return render(request, 'user/index.html', {'user': user, 'friendList': friendList,'profilePhotoList':profilePhotoList})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def startChat(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_To = request.GET['friendRequest_To']
            friendRequest_From = request.GET['friendRequest_From']

            userInfo = Usermaster.objects.filter(user_LoginId=friendRequest_To)
            friendList = FriendRequestmaster.objects.filter(friendRequest_From=request.session['session_Id'],
                                                            friendRequest_Action='accept')

            chatList = Msgmaster.objects.filter(msg_To=friendRequest_To,
                                                msg_From=friendRequest_From) | Msgmaster.objects.filter(
                msg_To=friendRequest_From, msg_From=friendRequest_To)
            print(chatList, "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")

            thisUser = int(request.session['session_Id'])
            thisFriend = int(friendRequest_To)
            print(thisUser, ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>from>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            print(thisFriend, ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>to>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            profilePhotoList = Usermaster.objects.all()

            return render(request, 'user/chat.html',
                          {'friendList': friendList, 'userInfo': userInfo, 'chatList': chatList, 'thisUser': thisUser,
                           'thisFriend': thisFriend,'profilePhotoList':profilePhotoList})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def insertMsg(request):
    try:
        if request.session.has_key('session_loginRole'):
            msg = request.POST['msg']
            msg_To = request.POST['msg_To']
            msg_From = request.session['session_Id']

            now = datetime.now()
            msgSendDate = now.date()
            msgSendTime = now.strftime("%I:%M:%S %p")

            chatmsg = Msgmaster(msg=msg, msg_From_id=msg_From, msg_To_id=msg_To, msgSendDate=msgSendDate,
                                msgSendTime=msgSendTime, msgSendBy=request.session['session_Id'])
            chatmsg.save()

            return redirect('/viewChat/' + msg_To)
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def viewChat(request, foo):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_To = get_object_or_404(Loginmaster, pk=foo)
            friendRequest_From = request.session['session_Id']

            userInfo = Usermaster.objects.filter(user_LoginId=friendRequest_To)
            friendList = FriendRequestmaster.objects.filter(friendRequest_From=request.session['session_Id'],
                                                            friendRequest_Action='accept')

            chatList = Msgmaster.objects.filter(msg_To=friendRequest_To,
                                                msg_From=friendRequest_From) | Msgmaster.objects.filter(
                msg_To=friendRequest_From, msg_From=friendRequest_To)

            thisUser = int(request.session['session_Id'])
            thisFriend = friendRequest_To.pk
            profilePhotoList = Usermaster.objects.all()
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>",profilePhotoList)
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", friendList)

            return render(request, 'user/chat.html',
                          {'friendList': friendList, 'userInfo': userInfo, 'chatList': chatList, 'thisUser': thisUser,
                           'thisFriend': thisFriend,'profilePhotoList':profilePhotoList})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def delete(request):
    try:
        if request.session.has_key('session_loginRole'):
            id = request.GET['id']
            msg_To = request.GET['msg_To']
            # print("????????????????????????????????????????????????????????????????????????????????????????????", id, msg_To)

            deleteChat = Msgmaster.objects.get(pk=id)
            deleteChat.delete()

            return redirect('/viewChat/' + msg_To)
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def deleteAll(request):
    try:
        if request.session.has_key('session_loginRole'):
            thisUser = request.GET['thisUser']
            thisFriend = request.GET['thisFriend']
            print("????????????????????????????????????????????????????????????????????????????????????????????",
                  thisUser,
                  thisFriend)

            removeAllChat = Msgmaster.objects.filter(msg_To=thisUser,
                                                     msg_From=thisFriend) | Msgmaster.objects.filter(
                msg_To=thisFriend, msg_From=thisUser)
            removeAllChat.delete()

            return redirect('/viewChat/' + thisFriend)
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)

friends/views.py
from django.shortcuts import render, redirect
from django.contrib.sessions.models import Session
from django.http import HttpResponse
from login.models import Loginmaster, Usermaster
from .models import FriendRequestmaster, Usermaster
from chat.models import Msgmaster


# Create your views here.

def loadFriends(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest = FriendRequestmaster.objects.filter(friendRequest_To=request.session['session_Id'],
                                                               friendRequest_Action='pending')
            profilePhotoList = Usermaster.objects.all()
            return render(request, 'user/friends.html', {'friendRequest': friendRequest,'profilePhotoList':profilePhotoList})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def insertFriendRequest(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_To = request.POST['friendRequest_To']
            friendRequest_From = request.session['session_Id']
            friendRequest_MSG = request.POST['friendRequest_MSG']
            friendRequest_Action = 'pending'

            friendRequest_To = Loginmaster.objects.filter(loginUserName=friendRequest_To)
            if len(friendRequest_To) != 0:
                friendRequest_To = friendRequest_To[0].id

                r1 = FriendRequestmaster.objects.filter(friendRequest_To_id=friendRequest_To,
                                                        friendRequest_From_id=friendRequest_From,
                                                        friendRequest_Action='accept').exists()
                r2 = FriendRequestmaster.objects.filter(friendRequest_To_id=friendRequest_From,
                                                        friendRequest_From_id=friendRequest_To,
                                                        friendRequest_Action='accept').exists()
                r3 = FriendRequestmaster.objects.filter(friendRequest_To_id=friendRequest_To,
                                                        friendRequest_From_id=friendRequest_From,
                                                        friendRequest_Action='pending').exists()
                r4 = FriendRequestmaster.objects.filter(friendRequest_To_id=friendRequest_From,
                                                        friendRequest_From_id=friendRequest_To,
                                                        friendRequest_Action='pending').exists()

                if r1 == False:
                    if r3 == True:
                        friendRequest = FriendRequestmaster.objects.filter(
                            friendRequest_To=request.session['session_Id'],
                            friendRequest_Action='pending')
                        return render(request, 'user/friends.html',
                                      {'requestPending': 'you request in pening.', 'friendRequest': friendRequest})
                    if r4 == True:
                        friendRequest = FriendRequestmaster.objects.filter(
                            friendRequest_To=request.session['session_Id'],
                            friendRequest_Action='pending')
                        return render(request, 'user/friends.html',
                                      {'showRequest': 'Request already send to you', 'friendRequest': friendRequest})


                    elif r2 == False:
                        friendRequest = FriendRequestmaster(friendRequest_To_id=friendRequest_To,
                                                            friendRequest_From_id=friendRequest_From,
                                                            friendRequest_MSG=friendRequest_MSG,
                                                            friendRequest_Action=friendRequest_Action)
                        friendRequest.save()
                        return redirect('/loadFriends')
                    elif r2 == True:
                        friendRequest = FriendRequestmaster.objects.filter(
                            friendRequest_To=request.session['session_Id'],
                            friendRequest_Action='pending')
                        return render(request, 'user/friends.html',
                                      {'alreadyFriend': 'you both are already friends.',
                                       'friendRequest': friendRequest})



                else:
                    friendRequest = FriendRequestmaster.objects.filter(friendRequest_To=request.session['session_Id'],
                                                                       friendRequest_Action='pending')
                    return render(request, 'user/friends.html',
                                  {'alreadyFriend': 'you both are already friends.', 'friendRequest': friendRequest})
            else:
                friendRequest = FriendRequestmaster.objects.filter(friendRequest_To=request.session['session_Id'],
                                                                   friendRequest_Action='pending')
                return render(request, 'user/friends.html',
                              {'userNotFound': 'This User is not Available.', 'friendRequest': friendRequest})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def viewRequestProfile(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_To = request.GET['friendRequest_To']
            userProfile = Usermaster.objects.filter(user_LoginId=friendRequest_To)

            friendRequest = FriendRequestmaster.objects.filter(
                friendRequest_To=request.session['session_Id'], friendRequest_Action='pending')
            profilePhotoList = Usermaster.objects.all()

            return render(request, 'user/friends.html', {'userProfile': userProfile, 'friendRequest': friendRequest,'profilePhotoList':profilePhotoList})
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def accept(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_From = request.GET['friendRequest_From']

            friendRequest = FriendRequestmaster.objects.get(friendRequest_From_id=friendRequest_From,
                                                            friendRequest_To_id=request.session['session_Id'])
            friendRequest.friendRequest_Action = 'accept'
            friendRequest.save()
            duplicate = FriendRequestmaster(friendRequest_To_id=friendRequest_From,
                                            friendRequest_From_id=request.session['session_Id'],
                                            friendRequest_Action='accept')
            duplicate.save()

            return redirect('/loadFriends')
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def reject(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_From = request.GET['friendRequest_From']
            friendRequest = FriendRequestmaster.objects.get(friendRequest_From_id=friendRequest_From,
                                                            friendRequest_To_id=request.session['session_Id'])
            friendRequest.delete()

            return redirect('/loadFriends')
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)


def removeFriend(request):
    try:
        if request.session.has_key('session_loginRole'):
            friendRequest_From = request.GET['thisUser']
            friendRequest_To = request.GET['thisFriend']

            removeFriendList = FriendRequestmaster.objects.filter(friendRequest_From=friendRequest_From,
                                                                  friendRequest_To=friendRequest_To) | FriendRequestmaster.objects.filter(
                friendRequest_To=friendRequest_From, friendRequest_From=friendRequest_To)
            removeFriendList.delete()

            removeAllChat = Msgmaster.objects.filter(msg_To_id=friendRequest_To,
                                                     msg_From_id=friendRequest_From) | Msgmaster.objects.filter(
                msg_To_id=friendRequest_From, msg_From_id=friendRequest_To)
            removeAllChat.delete()

            return redirect('/loadChat')
        else:
            return redirect('/')
    except Exception as ex:
        print(ex)

templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>
    <!-- SEO Meta Tags-->
    <meta name="keywords" content="quicky, chat, messenger, conversation, social, communication"/>
    <meta name="description"
          content="Quicky is a Bootstrap based modern and fully responsive Messaging template to help build Messaging or Chat application fast and easy."/>
    <meta name="subject" content="communication">
    <meta name="copyright" content="frontendmatters">
    <meta name="revised" content="Sunday, July 18th, 2010, 5:15 pm"/>
    <title>{% block title %}Quicky - HTML Chat Template{% endblock %}</title>
    <!-- Favicon and Touch Icons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'userResources/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'userResources/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'userResources/images/favicon-16x16.png' %}">
    <link rel="shortcut icon" href="./../favicon.ico"/>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{% static 'userResources/css/inter.css' %}">
    <link rel="stylesheet" href="{% static 'userResources/css/app.min.css' %}">
</head>

<body class="chats-tab-open">

<!-- Main Layout Start -->
<div class="main-layout">
    <!-- Navigation Start -->
    <div class="navigation navbar navbar-light bg-primary">
        <!-- Logo Start -->
        <a class="d-none d-xl-block bg-light rounded p-1" href="#">
            <!-- Default :: Inline SVG -->
            <svg height="30" width="30" viewBox="0 0 512 511">
                <g>
                    <path d="m120.65625 512.476562c-7.25 0-14.445312-2.023437-20.761719-6.007812-10.929687-6.902344-17.703125-18.734375-18.117187-31.660156l-1.261719-41.390625c-51.90625-46.542969-80.515625-111.890625-80.515625-183.992188 0-68.816406 26.378906-132.101562 74.269531-178.199219 47.390625-45.609374 111.929688-70.726562 181.730469-70.726562s134.339844 25.117188 181.730469 70.726562c47.890625 46.097657 74.269531 109.382813 74.269531 178.199219 0 68.8125-26.378906 132.097657-74.269531 178.195313-47.390625 45.609375-111.929688 70.730468-181.730469 70.730468-25.164062 0-49.789062-3.253906-73.195312-9.667968l-46.464844 20.5c-5.035156 2.207031-10.371094 3.292968-15.683594 3.292968zm135.34375-471.976562c-123.140625 0-216 89.816406-216 208.925781 0 60.667969 23.957031 115.511719 67.457031 154.425781 8.023438 7.226563 12.628907 17.015626 13.015625 27.609376l.003906.125 1.234376 40.332031 45.300781-19.988281c8.15625-3.589844 17.355469-4.28125 25.921875-1.945313 20.132812 5.554687 41.332031 8.363281 63.066406 8.363281 123.140625 0 216-89.816406 216-208.921875 0-119.109375-92.859375-208.925781-216-208.925781zm-125.863281 290.628906 74.746093-57.628906c5.050782-3.789062 12.003907-3.839844 17.101563-.046875l55.308594 42.992187c16.578125 12.371094 40.304687 8.007813 51.355469-9.433593l69.519531-110.242188c6.714843-10.523437-6.335938-22.417969-16.292969-14.882812l-74.710938 56.613281c-5.050781 3.792969-12.003906 3.839844-17.101562.046875l-55.308594-41.988281c-16.578125-12.371094-40.304687-8.011719-51.355468 9.429687l-69.554688 110.253907c-6.714844 10.523437 6.335938 22.421874 16.292969 14.886718zm0 0"
                          data-original="#000000" class="active-path" data-old_color="#000000" fill="#665dfe"/>
                </g>
            </svg>

            <!-- Alternate :: External File link -->
            <!-- <img class="injectable" src="./../assets/media/logo.svg" alt=""> -->
        </a>
        <!-- Logo End -->

        <!-- Main Nav Start -->
        <ul class="nav flex-row flex-grow-1 justify-content-between flex-xl-column justify-content-xl-center">

            <!-- Chats Tab Start -->
            <li>
                <a href="{% url 'chat:loadChat' %}" style="color: white">
                    <!-- Default :: Inline SVG -->
                    <svg class="hw-24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                    </svg>

                    <!-- Alternate :: External File link -->
                </a>
            </li>
            <!-- Chats Tab End -->
            <br><br>
            <!-- Friends Tab Start -->
            <li>
                <a href="{% url 'friends:loadFriends' %}" style="color: white">
                    <!-- Default :: Inline SVG -->
                    <svg class="hw-24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"/>
                    </svg>

                    <!-- Alternate :: External File link -->
                    <!-- <img class="injectable hw-24" src="./../assets/media/heroicons/outline/userResourcess.svg" alt="Friends icon"> -->
                </a>
            </li>
            <!-- Friends Tab End -->
            <br><br>

            <!-- Profile Tab Start -->
            <li>
                <a href="{% url 'myprofile:loadMyProfile' %}" style="color: white">
                    <!-- Default :: Inline SVG -->
                    <svg class="hw-24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>

                    <!-- Alternate :: External File link -->
                </a>
            </li>
            <!-- Profile Tab End -->
        </ul>
        <!-- Main Nav End -->
    </div>
    <!-- Navigation End -->

    {% block content %}

    {% endblock %}
</div>
<!-- Main Layout End -->

<!-- Javascript Files -->
<script src="{% static 'userResources/js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'userResources/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'userResources/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'userResources/js/svg-inject.min.js' %}"></script>
<script src="{% static 'userResources/js/modal-steps.min.js' %}"></script>
<script src="{% static 'userResources/js/app.js' %}"></script>
<script>
    // Scroll to end of chat
    document.querySelector('.chat-finished').scrollIntoView({
        block: 'end',               // "start" | "center" | "end" | "nearest",
        behavior: 'auto'          //"auto"  | "instant" | "smooth",
    });


</script>


</body>

</html>

templates/user/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>
    <!-- SEO Meta Tags-->
    <meta name="keywords" content="quicky, chat, messenger, conversation, social, communication"/>
    <meta name="description"
          content="Quicky is a Bootstrap based modern and fully responsive Messaging template to help build Messaging or Chat application fast and easy."/>
    <meta name="subject" content="communication">
    <meta name="copyright" content="frontendmatters">
    <meta name="revised" content="Sunday, July 18th, 2010, 5:15 pm"/>
    <title>Sign In</title>
    <!-- Favicon and Touch Icons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'userResources/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'userResources/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'userResources/images/favicon-16x16.png' %}">
    <link rel="shortcut icon" href="./../favicon.ico"/>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{% static 'userResources/css/inter.css' %}">
    <link rel="stylesheet" href="{% static 'userResources/css/app.min.css' %}">
</head>

<body class="authentication-page">

<!-- Main Layout Start -->
<div class="main-layout card-bg-1">
    <div class="container d-flex flex-column">
        <div class="row no-gutters text-center align-items-center justify-content-center min-vh-100">
            <div class="col-12 col-md-6 col-lg-5 col-xl-4">
                <h1 class="font-weight-bold">Sign in</h1>
                <p class="text-dark mb-3">We are Different, We Make You Different.</p>
                <form class="mb-3" action="insertLogin" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email" class="sr-only">Email Address</label>
                        <input type="email" name="userName" class="form-control form-control-md" id="email"
                               placeholder="Enter your email" required>
                    </div>
                    <div class="form-group">
                        <label for="password" class="sr-only">Password</label>
                        <input type="password" name="password" class="form-control form-control-md" id="password"
                               placeholder="Enter your password" required>
                    </div>
                    <div class="form-group d-flex justify-content-between">

                        <a class="font-size-sm" href="{% url 'login:forgotPassword' %}" style="text-align: right">Forgot
                            password</a>
                    </div>
                    {% if userNotExist %}
                        <h4>{{ userNotExist }}</h4>
                    {% endif %}
                    <button class="btn btn-primary btn-lg btn-block text-uppercase font-weight-semibold" type="submit">
                        Sign in
                    </button>
                </form>

                <p>Don't have an account? <a class="font-weight-semibold" href="loadRegister">Sign up</a>.</p>
            </div>
        </div>
    </div>
</div>
<!-- Main Layout End -->


<!-- Javascript Files -->
<script src="{% static 'userResources/js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'userResources/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'userResources/js/svg-inject.min.js' %}"></script>
<script src="{% static 'userResources/js/app.js' %}"></script>

</body>

</html>